<?php

/**
 * Implementation of hook_hosting_tasks
 */
function hosting_tasks_extra_hosting_tasks() {
  $tasks = array();

  $tasks['site']['flush_cache'] = array(
    'title' => t('Flush all caches'),
    'description' => t('Flushes all caches on the site.'),
  );
  $tasks['site']['rebuild_registry'] = array(
    'title' => t('Rebuild registry'),
    'description' => t('Rebuilds the registry and flushes all caches on the site.'),
  );
  $tasks['site']['run_cron'] = array(
    'title' => t('Run cron'),
    'description' => t('Runs cron on the site.'),
  );
  $tasks['site']['update'] = array(
    'title' => t('Update'),
    'description' => t('Run updates on this site.'),
    'dialog' => TRUE,
  );
  $tasks['server']['flush_drush_cache'] = array(
    'title' => t('Flush Drush cache'),
    'description' => t('Flush the Drush cache on this (web) server.'),
  );

  return $tasks;
}


/**
 * Implementation of hook_perm()
 */
function hosting_tasks_extra_perm() {
  return array(
    'create rebuild_registry task',
    'create flush_cache task',
    'create run_cron task',
    'create update task',
    'create flush_drush_cache task',
  );
}

/**
 * Implements hosting_task_TASK_TYPE_form().
 */
function hosting_task_update_form($node) {
  // Gather a list of operations to execute.
  $all_ops = module_invoke_all('hosting_task_update_ops');
  uasort($all_ops, 'element_sort');
  $value = '<div>The following operations will be executed on <em>' . $node->title . '</em>:<br /><ul>';
  foreach ($all_ops as $item) {
    $value .= '<li>' . $item['#description'] . '</li>';
  }
  $value .= '</ul></div>';
  $form['operations'] = array(
    '#value' => $value,
  );
  return $form;
}

/**
 * Implements hook_hosting_task_update_ops().
 *
 * @see: hosting_task_update_form().
 */
function hosting_tasks_extra_hosting_task_update_ops() {
  return array(
    'site update' => array(
      '#description' => 'Run site updates (update.php).',
      '#weight' => 0,
    )
  );
}
