<?php

/**
 * Implementation of hook_hosting_tasks
 */
function hosting_tasks_extra_hosting_tasks() {
  $tasks = array();

  $tasks['site']['flush_cache'] = array(
    'title' => t('Flush cache'),
    'description' => t('Flushes cache on the site.'),
  );
  $tasks['site']['rebuild_registry'] = array(
    'title' => t('Rebuild Registry'),
    'description' => t('Rebuilds the registry on the site.'),
  );

  return $tasks;
}


/**
 * Implementation of hook_perm()
 */
function hosting_tasks_extra_perm() {
  return array(
    'create rebuild_registry task',
    'create flush_cache task',
  );
}

